### ISSUE TITLE
core: Carrinho de produtos

### ISSUE THREAD

**Issue by bootcampnet2024** [bootcampnet2024/eShop#20]
Eu como usuário do site quero ter a possibilidade de incluir os produtos em um carrinho para posteriormente realizar o pedido.

Criterios de aceite: 
- [x] #27
- [ ] Estrutura de testes do microserviço
- [x] #28
- [ ] Estrutura para identificar o usuário logado
- [x] #29
- [ ] Possibilidade de listar os itens do carrinho de compras 

Critérios reversos:
- [ ] Front não é parte da estoria.

**Comment by EduardoTCaetano** [comment]
#15 #16 #17 #27 #28 #26
