### ISSUE TITLE
web: mudar comportamento da pagina de registro

### ISSUE THREAD

**Issue by victortedesco** [bootcampnet2024/eShop#81]
Critérios de Aceite:
- [x] Adicionar input para Nome Completo
- [x] Adicionar input para Telefone
- [x] Separar Endereço em Rua, Cidade, Estado, País. (Como talvez essa issue #72 seja desenvolvida, podemos remover esse campo dessa página)
- [x] Trocar o plano de fundo por uma imagem em alta resolução e redimensiona-la

**Comment by sofiabucci** [comment]
feito
