### ISSUE TITLE
web: mudar comportamento da página de login

### ISSUE THREAD

**Issue by victortedesco** [bootcampnet2024/eShop#82]
Critérios de Aceite:
- [x] Adicionar mensagem de erro na página quando o usuário e/ou senha for incorreto
- [x] Mudar o estilo da página, como o posicionamento dos elementos, bordas dos inputs e o tamanho dos botões.
- [x] Trocar o plano de fundo por uma imagem em alta resolução e redimensiona-la (Também citada na issue #81)

**Comment by sofiabucci** [comment]
feito
